# Generated by Django 4.0.3 on 2024-07-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_trainingdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='message',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='response',
        ),
        migrations.AddField(
            model_name='chat',
            name='role',
            field=models.TextField(default='rand'),
            preserve_default=False,
        ),
    ]
